msrv = "1.89"
cognitive-complexity-threshold = 20
too-many-lines-threshold = 100
too-many-arguments-threshold = 6
type-complexity-threshold = 200
avoid-breaking-exported-api = false
allow-unwrap-in-tests = true
allow-expect-in-tests = true
allow-panic-in-tests = true
allow-print-in-tests = true
allow-indexing-slicing-in-tests = true
